### ISSUE TITLE
Show the urlTemplate of External IDs in the edit form

### ISSUE THREAD

**Issue by dpancic** [SSHOC/sshoc-marketplace-frontend#123]
In GitLab by @KlausIllmayer on Oct 24, 2022, 13:34

Currently, it is unclear to contributors, that there are `urlTemplates` for `External IDs`. As an example, we defined for the external ID service `GitHub` the url template `https://github.com/{source-item-id}`. We expect that contributors respect this url template and therefore do not add the `https://github.com/`-part to their entry. But currently, the frontend does not give any indications, that such url template exists and there are also no instructions, how to interpret it. Is there a quick solution possible for this issue? I don't mind how it is solved in the UI, maybe it is enough that there is a information label: `Please enter the identifier based on the url template: {urlTemplate}`

@laureD19 Do you have a proposal how to solve it in the edit form?

**Comment by stefanprobst** [comment]
> maybe it would be better to separate both sentences, but to have an opinion on it I need to see it live

@KlausIllmayer opinions?

**Comment by KlausIllmayer** [comment]
The only minor irritation for me is that the initial information does not clearly communicate, where the placeholder is, e.g. it says for GitHub `The generated ID will be: https://github.com/.` Not sure if it makes sense to clearly mark, that behind is the placeholder for the text to be entered.

Additionally, if you don't enter data and leave the field, you will get the warning "Field must not be empty" which overwrites the information bout the generated ID.

Both are really minor, as it all become clear when you start to type text in the input field. I propose to look how often errors happen for this fields (e.g. entering the full URL and not the id-part) in the next months, if we see problems, we should re-think it - otherwise lets go for now with the current solution.
