### ISSUE TITLE
sort actor and concept combobox values alphabetically

### ISSUE THREAD

**Issue by dpancic** [SSHOC/sshoc-marketplace-frontend#88]
In GitLab by @vronk on Dec 23, 2021, 10:47

Currently with a longer vocabulary, user in edit form has to know what to start typing to get a suggestions.
There has to be a way to see full list of vocabularies
- in minimal case (vocabulary specific) link to https://vocabs.sshopencloud.eu/vocabularies/en/  (or whatever they are published, e.g. TaDiRAH in https://vocabs.dariah.eu/tadirah/en/)
- or some listing of the whole vocabulary as listed by the API.

Ideas how to implement?

(notify: @KlausIllmayer , @laureD19 @vronk

**Comment by stefanprobst** [comment]
requires https://github.com/SSHOC/sshoc-marketplace-backend/issues/171

**Comment by KlausIllmayer** [comment]
https://github.com/SSHOC/sshoc-marketplace-backend/issues/171 was approved and is now available on all instances. There is now an order-parameter for `api/actor-search` and `api/concept-search`

**Comment by stefanprobst** [comment]
fixed by https://github.com/SSHOC/sshoc-marketplace-frontend/commit/14d466267f3aec31996a25c92e80c07d53223d79

**Comment by KlausIllmayer** [comment]
Confirm, that it works on dev, can be applied to stage and production.

Side note only for documentation: It is already helpful, but due to some of our vocabularies the effect is not as good, as I hoped, e.g. in disciplines we do have many concepts, searching for something like `History` gives you back a lot of values as it searches for history as substring and with the alphabetical order you will see at first "Ancient history".
